config/routes.rb
Rails.application.routes.draw do
  get 'info/index'
  devise_for :users
  root to: "tdc#index"
  resources :info
  resources :tdc do
    collection do
      resources :category
      resources :price
    end
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  include ActiveHash::Associations
  has_many :shops

  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '焼肉' },
    { id: 3, name: '寿司' },
    { id: 4, name: 'ラーメン' },
    { id: 5, name: '居酒屋' },
    { id: 6, name: 'cafe' },
    { id: 7, name: 'その他' }
  ]
end

app/models/price.rb
class Price < ActiveHash::Base
  include ActiveHash::Associations
  has_many :shops

  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '0 ~ 1000円' },
    { id: 3, name: '1000 ~ 2000円' },
    { id: 4, name: '2000 ~ 3000円' },
    { id: 5, name: '3000 ~ 5000円' },
    { id: 6, name: '5000 ~ 10000円' },
    { id: 7, name: '10000円以上' }
  ]
end

app/models/prise.rb
class Prise < ActiveHash::Base
  include ActiveHash::Associations
  has_many :shops

  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '0 ~ 1000円' },
    { id: 3, name: '1000 ~ 2000円' },
    { id: 4, name: '2000 ~ 3000円' },
    { id: 5, name: '3000 ~ 5000円' },
    { id: 6, name: '5000 ~ 10000円' },
    { id: 7, name: '10000円以上' }
  ]
end

app/models/shop.rb
class Shop < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :price
  belongs_to :category

  has_one_attached :image

  with_options presence: true do
    validates :shop_name
    validates :info
    validates :image
  end

  with_options numericality: { other_than: 1 } do
    validates :category_id
    validates :price_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops
  validates :nickname, presence: true, length: { maximum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def create
  end

  def new
    @user = User.new
  end

  def destroy
    tweet = User.find(params[:id])
    tweet.destroy
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @shops = Shop.where(category_id: params[:category_id])
  end

  def destroy
    @note = Shop.find(params[:id])
    @note.destroy
    redirect_to root_path
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def index
    render layout: nil
  end
end

app/controllers/price_controller.rb
class PriceController < ApplicationController
  def index
    @shops = Shop.where(price_id: params[:price_id])
  end

  def destroy
    @note = Shop.find(params[:id])
    @note.destroy
    redirect_to root_path
  end
end

app/controllers/tdc_controller.rb
class TdcController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @shops = Shop.all
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  private

  def shop_params
    params.require(:shop).permit(:shop_name, :info, :price_id, :category_id, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/price_helper.rb
module PriceHelper
end

app/helpers/tdc_helper.rb
module TdcHelper
end

app/views/category/index.html.erb
<h2 class='kensaku'>検索結果</h2>
<% @shops.each do |shop| %>
<div class='category-page'>
  <%= image_tag shop.image, class: "item-img" %>
  <div class='shop-text'>
  <%= shop.category.name %>
  </div>
  <div class='shop-text'>
  <%= shop.shop_name %>
  </div>
  <div class='shop-text'>
  <%= shop.price.name %>
  </div>
  <div class='shop-info'>
  <%= shop.info %>
  </div>
  <%= link_to '削除', category_path(shop.id), method: :delete, class:'btn' %>
</div>
<% end %>

app/views/info/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>portforio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<div class='top'>
<h1>大内晴貴のポートフォリオ解説</h1>
</div>
<div class='p-box'>
  <h2>テーマ: 1からアプリを作るという経験をする。</h2>
  <p>使用した言語など</p>
  <div class='image-box'>
    <%= image_tag"スクリーンショット-2018-12-13-11.34.09.png", class:"images" %>
    <%= image_tag"download-1.png", class:"images" %>
    <%= image_tag"fd39f7be9f2aaa62e16506e9aa2882f4.png", class:"images" %>
    <%= image_tag"download-2.png", class:"images" %>
    <%= image_tag"square_274b1338-1884-4eb3-ad8f-bb159162c810.png", class:"images" %>
  </div>
  <div class='info'>
    <%= video_tag  "cd3052202d3041ecd26684f2f834a2cc.mp4",:controls => true, :loop => true,class:"videos" %>
    <div class="info-box">
    <p>こちらのアプリは私の地元豊田市の飲食店をスマホやラインで簡単に探せるアプリとなっております。</p>
    <p>見た目はシンプルで使いやすい物をイメージしました。特にデザインで意識したところは<span>凹凸の付け方</span>です。大手のwebサイトでは色の使い方で凹凸を表現しているように感じ自分も見様見真似ですが再現してみました</p>
    </div>
  </div>
  <div class='info'>
    <%= video_tag  "e93117c23e9544dcbca9a1376584bd95.mp4",:controls => true, :loop => true,class:"videos" %>
    <div class="info-box">
    <p>中もシンプルにこの様な感じです。</p>
    <p>画像の保存に関しては<span>S3</span>を使用しているので消えることはございません</p>
    </div>
  </div>
  <div class='info'>
    <%= video_tag  "7277fa43db537e6a86b5a2f5ab9ee480.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>公式ラインを追加することによって<span>ラインでお店を探す</span>ことができ<span>スマホなどでラインをダウンロードしている場合はすぐに「友達を追加する」のボタンがある画面にとびます。</span></p>
  </div>
  <div class='info'>
    <%= video_tag  "1217.t.mp4",:controls => true, :loop => true,:muted => true,class:"videos" %>
    <p>左の動画の様に特定の言葉を打って頂くと、それに合ったページを返してくれます。</p>
  </div>
  <div class='info'>
    <%= image_tag"eyecatch-2016-09-07-001.jpg", class:"videos" %>
    <p>AWSにてデプロイサクサク動きます。</p>
  </div>
  <div class='message'>
    <h2>感想</h2>
    <ul>
      <li>デザインの学習不足</li>
      <li>工数のかかりすぎ</li>
      <li>設計が甘い</li>
    </ul>
    <p>今回のアプリを作ってみてrubyの構造が頭の中で整理された感覚があったのと<span>canvaやlineとの同期</span>など経験ができそれらは非常によかったと思うがデータベース設計が甘かったり昨日の設計がうまくでいていなかったり経験不足を非常によく感じることができ経験としては良いものとなったと思います</p>
  </div>
  <%=link_to 'ポートフォリオを見に行く', "/", class:"back-btn" %>
</div>
<div class='p-box'>
  <h2>テーマ: gemを使用し高速でアプリを作成する</h2>
  <p>使用した言語など</p>
  <div class='image-box'>
    <%= image_tag"スクリーンショット-2018-12-13-11.34.09.png", class:"images" %>
    <%= image_tag"download-1.png", class:"images" %>
    <%= image_tag"fd39f7be9f2aaa62e16506e9aa2882f4.png", class:"images" %>
    <%= image_tag"download-2.png", class:"images" %>
  </div>
  <div class='info'>
    <%= video_tag  "5effe7b26882ba0ed504478a3edc9f2d.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>こちらのアプリは予約アプリとなっており先ほどのアプリと同時に使って頂くと非常に便利なアプリとなっております。ユーザー登録がないため<span>1分で予約が可能</span>です</p>
  </div>
  <div class='info'>
    <%= video_tag  "8624e0118d44cebca0b905124c0917f6.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>入力するだけで予約完了</p>
  </div>
  <div class='info'>
    <%= video_tag  "8c4dadeef51312bf8e78a3458792f507.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>店舗側からもメッセージを表示させることができます</p>
  </div>
  <div class='info'>
    <%= video_tag  "eecac90f627487215cd17dfef3fdfead.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>店舗側からは情報を編集することが出来ます</p>
  </div>
  <div class='info'>
    <%= image_tag"eyecatch-2016-09-07-001.jpg", class:"videos" %>
    <p>AWSにてデプロイサクサク動きます。</p>
  </div>
  <div class='message'>
    <h2>感想</h2>
    <ul>
      <li>スマホで見ると文字やボタンが小さい</li>
      <li>プロの仕事とは言えない</li>
    </ul>
    <p>今回のアプリをスマホで確認してみるとボタンや文字が小さく見にくいなどシンプルカレンダーが英語で使いずらいなど様々な問題点がありプロの仕事とは言えないという反省点が残りました。ですが今回のアプリ作成でgemの凄さが非常によくわかりました。実際に今回のアプリを<span>作成するまでに掛かった時間は3日</span>という結果になり非常によかったと思います。それとアプリ作成が２つ目ということもあり経験によって時間短縮ができたと思い改めて経験の大事さを感じました。</p>
  </div>
  <%=link_to 'ポートフォリオを見に行く', "http://52.69.74.174", class:"back-btn" %>
</div>
<div class='p-box'>
  <h2>テーマ: docker jquely javascriptを使用し作成する</h2>
  <p>使用した言語など</p>
  <div class='image-box'>
    <%= image_tag"スクリーンショット-2018-12-13-11.34.09.png", class:"images" %>
    <%= image_tag"download-1.png", class:"images" %>
    <%= image_tag"fd39f7be9f2aaa62e16506e9aa2882f4.png", class:"images" %>
    <%= image_tag"download-3.png", class:"images" %>
    <%= image_tag"js.png", class:"images" %>
    <%= image_tag"lfVWBmiW_400x400.png", class:"images" %>
  </div>
  <div class='info'>
    <%= image_tag"03_A04A7613-696x464.jpg", class:"videos" %>
    <p>メモアプリを作成、showroomの前田社長が書かれた<span>メモの魔力</span>という本の内容を参考に作成したメモアプリです。</p>
  </div>
  <div class='info'>
    <%= video_tag  "f46c5cf2aa1e76d286edddecdcaf89a1.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>jquelyを使用しオシャレな？ページを作成</p>
  </div>
  <div class='info'>
    <%= video_tag  "b41faf6948ba95f2277358367eaa4db7.mp4",:controls => true, :loop => true,class:"videos" %>
    <div class="info-box">
    <p>javascriptを使用し非同期通信を可能にしております。</p>
    <p>（現在デプロイされたアプリではエラーよってjavascriptが反映されていないため原因が解決しだい実装します。ローカルでは起動確認済、また画像に関してもデプロイ時反映されていないというエラーがありそれも原因が解決しだい実装します。）</p>
  </div>
  </div>
  <div class='info'>
    <%= video_tag  "e7ce8e4b4f580afe6636702b38c98f8f.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>ノートの中身はこのようになっており前田さんのノートの取り方をそのまま再現できるようになっています。cssでノートを作成するのは難しかったですが意外と上手くいって本人は満足しています。</p>
  </div>
  
  <div class='message2'>
    <h2>感想</h2>
    <ul>
      <li>dockerを使用し環境構築することが少しだけ出来た。</li>
      <li>jquelyはイメージしたまま完璧に出来た。</li>
      <li>アプリとしてはめちゃくちゃ使いやすい！</li>
    </ul>
    <p>分かってはいたがdockerかなり難しかったので正直完璧に理解は出来ていない状況です。ですがdockerを使用し環境構築することで、<span>dockerという物自体に慣れることが出来き非常に良かった。</span>jquelyはコードも書きやすくしっかりとアニメーションが出来そうだったのでやってみましたが、想像以上に上手く簡単に出来たのでよかったです！非同期通信に関してはなかなか理解に時間が掛かってしまいましたが何とか形にすることが出来ました。アプリ本体に関しては、ほんとに使いやすい！実用性が非常にあり自分は毎日多様している程です。なかなか<span>メモにメモをできるアプリがなかった</span>ため作成したのですがとても良かったです。</p>
  </div>
  <%=link_to 'ポートフォリオを見に行く', "https://business-app-32596.herokuapp.com/", class:"back-btn" %>
</div>
<h3 class="apri">現在自分がやっていること</h3>
<div class='info2'>
    <%= image_tag"swift-og.png", class:"apuri" %>
    <p>現在私は、swiftを学習しています。webアプリ制作は非常におもしろかったのですが、それと同時にiosアプリにも興味が沸き現在学習中です。現在作成しているアプリが以下の物になります！</p>
</div>

<div class='p-box'>
  <h2>テーマ: youtube API を利用しアプリを作成、Firebaseに情報を保存。</h2>
  <div class='info'>
    <%= video_tag  "52ba03411e5d8d5dc56d1c2f26232d29.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>Main.storyboardはこの様になっています。</p>
  </div>
  <div class='info'>
    <%= video_tag  "6c663ba9ce6fe74f7bbe1260651ccec5.mp4",:controls => true, :loop => true,class:"videos" %>
    <p><span>動くグラデーション</span>を使用し、ユーザー登録画面を作成</p>
  </div>
  <div class='info'>
    <%= video_tag  "d897e78254c697db87b94c0595cd96cc.mp4",:controls => true, :loop => true,class:"videos" %>
    <div class="info-box">
    <p>プロフィールを作成、<span>アルバムを開いたりカメラを起動させることができます</span></p>
    <p>スマホであればしっかりとカメラも起動できます！</p>
  </div>
  </div>
  <div class='info'>
    <%= video_tag  "6d50925baabd6a49f99bf1989c50369f.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>youtube API を使用しているので検索をかければ動画が出てきます！</p>
  </div>
  <div class='info'>
    <%= video_tag  "8b053c1b3e39571d8fad3735a886467a.mp4",:controls => true, :loop => true,class:"videos" %>
    <p>現在はタグ機能や共有機能を作成中です！</p>
  </div>
</div>
<h3 class="apri">自分が使った便利なアプリ一覧</h3>
<div class='info2'>
    <%= image_tag"mzl.wcnerfrh.jpg", class:"apuri" %>
    <p>こちらはATOK Padというアプリで、optionnを二回押すだけでメモ帳が出てきてくれるため最速でメモをとることが出来ます！</p>
</div>
<div class='info2'>
    <%= image_tag"20190416024534.png", class:"apuri" %>
    <p>こちらはshiftitというアプリで、画面分割をキー割り当てをすることで行えるアプリになっております。これによって作業スピードが飛躍的に上がりました！</p>
</div>
<div class='info2'>
    <%= image_tag"trello-mark-blue.png", class:"apuri" %>
    <p>Trelloはタスク管理に非常に役立ってくれます。これによって付箋でタスクを管理しなくて良くなり非常に助かります！</p>
</div>
<h3 class="apri">最後に</h3>
<div class='info3'>
    <p class="last">ここまで読んで頂き誠にありがとうございます！少しでも良いなと思っていただければ幸いです。</p>
    <p class="last">もし御社に入社させて頂いた場合には、自分の武器である若さ、積極性、主体性を発揮し御社の利益に全力で貢献致しますのでよろしくお願いします。</p>
    <p class="last">良いお返事を心よりお待ちしております！</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TDC32596</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <div class= 'line'>
    <div class= 'display'>
      <%= image_tag("24bae56cf719cbf66e92540cfa88e9bb.png", class:"mini-logo") %>
      <p class= 'line-text'>TDCラインアカウント</p>
    </div>
    <div class= 'display'>
      <p class='line-log'> 登録はこちらをタッチ→</p>
      <%= link_to image_tag("315f499d73553a11185b0ce15bde9011.png", class:"friend"), "https://lin.ee/7p4GyTL" %>
      <%= link_to image_tag("e29df0c5db1d6c1590d9645d24ffb17d.png", class:"friend"), "https://liff.line.me/" %>
    </div>
    </div>
    <div class= 'second-header'>
      <%= link_to image_tag("24bae56cf719cbf66e92540cfa88e9bb.png", class:"second-logo"), "/" %>
      <p class= 'TBD-text'>私たちは豊田市に住む飲食店経営者とそのお客様を応援しております。</p>
          <%# ログインしているときは以下を表示するようにしましょう %>
          <div class= 'user'>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__btn %>
              
            </div>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <% else %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
          <% end %>
          </div>
    </div>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/price/index.html.erb
<div class = "back">
  <% @shops.each do |shop| %>
  <div class='category-page'>
    <%= image_tag shop.image, class: "item-img" %>
    <div class='shop-text'>
    <%= shop.category.name %>
    </div>
    <div class='shop-text'>
    <%= shop.shop_name %>
    </div>
    <div class='shop-text'>
    <%= shop.price.name %>
    </div>
    <div class='shop-info'>
        <%= shop.info %>
    </div>
    <%= link_to '削除', price_path(shop.id), method: :delete, class:'btn' %>
  </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/tdc/index.html.erb
<div class= 'back-color'>
  <div class= 'top-images'>
    <%= image_tag("ラインを登録してお店探し！.png", class:"image-ttop") %>
  </div>
  <div class= 'border'>
    <div class= 'category-text'>
      <h2 class= 'text'>カテゴリーから探す</h2>
    </div>
    <div class ='category-box'>
      <div class= 'category'>
        <%= link_to image_tag("焼肉 (2).png", class:"cate"), category_index_path(category_id: 2) %>
      </div>
      <div class= 'category'>
        <%= link_to image_tag("寿司.png", class:"cate"), category_index_path(category_id: 3) %>
      </div>
      <div class= 'category'>
        <%= link_to image_tag("ラーメン.png", class:"cate"), category_index_path(category_id: 4) %>
      </div>
    </div>
    <div class ='category-box'>
      <div class= 'category'>
        <%= link_to image_tag("居酒屋.png", class:"cate"), category_index_path(category_id: 5) %>
      </div>
      <div class= 'category'>
        <%= link_to image_tag("cafe.png", class:"cate"), category_index_path(category_id: 6) %>
      </div>
      <div class= 'category'>
        <%= link_to image_tag("加.png", class:"cate"), category_index_path(category_id: 7) %>
      </div>
    </div>
  </div>
  <div class= 'border'>
    <div class= 'category-text'>
      <h2 class= 'text'>値段から探す</h2>
    </div>
    <div class ='category-box'>
      <div class= 'category'>
        <%= link_to image_tag("0 _ 1000円.png", class:"cate"), price_index_path(price_id: 2) %>
      </div>
      <div class= 'category'>
        <%= link_to image_tag("1000円 _ 2000円.png", class:"cate"), price_index_path(price_id: 3) %>
      </div>
      <div class= 'category'>
        <%= link_to image_tag("2000円 _ 3000円.png", class:"cate"), price_index_path(price_id: 4) %>
      </div>
    </div>
    <div class ='category-box'>
      <div class= 'category'>
        <%= link_to image_tag("3000円 _ 5000円.png", class:"cate"), price_index_path(price_id: 5) %>
      </div>
      <div class= 'category'>
        <%= link_to image_tag("5000円 _ 10000円.png", class:"cate"), price_index_path(price_id: 6) %>
      </div>
      <div class= 'category'>
        <%= link_to image_tag("10000円 _.png", class:"cate"), price_index_path(price_id: 7) %>
      </div>
    </div>
  </div>
  <div class= 'border'>
    <h2 class= 'shop-top'>TDCでお店を紹介してみませんか？</h2>
    <p class= 'shop-form'>1分で簡単登録！！今すぐお店を登録しましょう！！</p>
    <div class='shop-btn'>
      <%= link_to 'お店を登録', new_tdc_path, class: "item-red-btn" %>
    </div>
  </div>
  <div class= 'border2'>
    <%= link_to '説明欄', info_index_path, class: "btn" %>
  </div>
</div>

app/views/tdc/new.html.erb
<div class="items-sell-main">
    <h2 class="items-sell-title">店舗の情報を入力</h2>
    <%= form_with model:@shop, url: tdc_index_path, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 出品画像 %>
    <div class="info-info">
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        店舗名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :shop_name, class:"items-text", id:"item-name", placeholder:"店舗名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          店舗の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"店舗の説明（必須 1,000文字まで）（住所、料理、席数、予約のできるサイトのURL、電話番号、など）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <%# item_category_idで保存先を指定してあげて ItemCategory.allでモデルの全てを持ってきてそのあとは何を保存するか指定する%>
        <div class="weight-bold-text">
          値段
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:price_id, Price.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    
    <%# /商品の詳細 %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
  </div>